# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'vimarin-boiler-usach'
    scannerMode: 'MSBuild'
    projectKey: 'vimarin-boiler_spring-boot-kubernetes'
    projectName: 'spring-boot-kubernetes'
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true
    sqMavenPluginVersionChoice: 'latest'
    failWhenBugsFound: true
  displayName: SonarCloud Analysis
    
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
- task: sonarcloud-buildbreaker@2
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'vimarin-boiler-usach'
- task: dependency-check-build-task@6
  inputs:
    projectName: 'spring-boot-kubernetes'
    scanPath: '$(Build.SourcesDirectory)'
  displayName: Dependency Check

- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'
  displayName: Install Docker
- task: Docker@2
  inputs:
    containerRegistry: 'Docker'
    repository: 'vimarin/spring-boot-kubernetes'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'
  displayName: Build Docker

- script: | 
    sudo apt-get install -y rpm
    wget https://github.com/aquasecurity/trivy/releases/download/v0.27.1/trivy_0.27.1_Linux-64bit.deb
    sudo dpkg -i trivy_0.27.1_Linux-64bit.deb
    trivy image --format template --template "@/usr/local/share/trivy/templates/html.tpl" -o trivy-report.html vimarin/spring-boot-kubernetes:latest
  displayName: Image Scan
- task: Docker@2
  inputs:
    containerRegistry: 'Docker'
    repository: 'vimarin/spring-boot-kubernetes'
    command: 'push'
    tags: 'latest'
  displayName: Publish Docker

