# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'vimarin-boiler-usach'
    scannerMode: 'MSBuild'
    projectKey: 'vimarin-boiler_spring-boot-kubernetes'
    projectName: 'spring-boot-kubernetes'
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true
    sqMavenPluginVersionChoice: 'latest'
    failWhenBugsFound: true
    
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
- task: dependency-check-build-task@6
  inputs:
    projectName: 'spring-boot-kubernetes'
    scanPath: '$(Build.SourcesDirectory)'

- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'
- task: Docker@2
  inputs:
    containerRegistry: 'Docker'
    repository: 'vimarin/spring-boot-kubernetes'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'

